#!/bin/sh

. bootrr

TEST_CASE_ID="$1"
FILEPATH="$2"
TIMEOUT="${3:-1}"

if [ -z "${TEST_CASE_ID}" -o -z "${FILEPATH}" ]; then
	echo "Usage: $0 <test-case-id> <file path> [<timeout>]"
	exit 1
fi

if [ ! -e "${FILEPATH}" ]
then
	test_report_exit skip
fi

timeout ${TIMEOUT} cat "${FILEPATH}" || test_report_exit fail
timeout ${TIMEOUT} [ -z "$(cat "${FILEPATH}")" ] || test_report_exit fail

test_report_exit pass
