#!/bin/sh

. bootrr

TEST_CASE_ID="$1"
DEVICE="$2"
TIMEOUT="${3:-1}"

if [ -z "${TEST_CASE_ID}" -o -z "${DEVICE}" ]; then
	echo "Usage: $0 <test-case-id> <device> [<timeout>]"
	exit 1
fi

timeout ${TIMEOUT} [ -d /sys/class/mdio_bus/*/${DEVICE} ] || test_report_exit fail

test_report_exit pass
