ROOT_PATH = "KernelTCP"

[LOG]
# logging
LEVEL = "DEBUG"
PATH = "logs"
FORMAT = "%(process)d %(threadName)s %(thread)d %(asctime)s  %(filename)s : %(levelname)s  %(message)s"
DATE_FORMAT = "%Y-%m-%d %A %H:%M:%S"

[MYSQL]
USERNAME = "root"
PASSWORD = ""
HOST = "localhost"
PORT = 3306
DATABASE = "lkft"