#!/bin/sh

assert_driver_present imx-i2c-driver-present imx-i2c
assert_device_present imx-i2c-i2c0-probed imx-i2c 30a20000.*
assert_device_present imx-i2c-i2c3-probed imx-i2c 30a30000.*
assert_device_present imx-i2c-i2c3-probed imx-i2c 30a40000.*

assert_driver_present imx-uart-driver-present imx-uart
assert_device_present imx-uart-uart0-probed imx-uart 30860000.*
assert_device_present imx-uart-uart1-probed imx-uart 30880000.*
assert_device_present imx-uart-uart2-probed imx-uart 30890000.*

assert_driver_present imx6q-pcie-driver-present imx6q-pcie
assert_device_present imx6q-pcie-pcie0-probed imx6q-pcie 33c00000.*

assert_driver_present intel-igb-driver-present igb
assert_device_present intel-igb-probed igb 0001:01:00.0

assert_driver_present dwc3-driver-present dwc3
assert_device_present dwc3-usb0-probed dwc3 38100000.*
assert_device_present dwc3-usb1-probed dwc3 38200000.*

assert_driver_present imx8mq-usb-phy-driver-present imx8mq-usb-phy
assert_device_present imx8mq-usb-phy0-probed imx8mq-usb-phy 381f0040.*
assert_device_present imx8mq-usb-phy1-probed imx8mq-usb-phy 382f0040.*

assert_driver_present imx2-wdt-driver-present imx2-wdt
assert_device_present imx2-wdt-watchdog0-probed imx2-wdt 30280000.*

assert_driver_present imx-sdma-driver-present imx-sdma
assert_device_present imx-sdma-0-probed imx-sdma 302c0000.*
assert_device_present imx-sdma-1-probed imx-sdma 30bd0000.*

assert_driver_present imx8mq-pinctrl-driver-present imx8mq-pinctrl
assert_device_present imx8mq-pinctrl-0-probed imx8mq-pinctrl 30330000.*

assert_driver_present imx8mq-ccm-driver-present imx8mq-ccm
assert_device_present imx8mq-ccm-0-probed imx8mq-ccm 30380000.*

assert_driver_present imx_ocotp-driver-present imx_ocotp
assert_device_present imx_ocotp-0-probed imx_ocotp 30350000.*

assert_driver_present sdhci-esdhc-imx-driver-present sdhci-esdhc-imx
assert_device_present sdhci-esdhc-imx-mmc0-probed sdhci-esdhc-imx 30b40000.*
assert_device_present sdhci-esdhc-imx-mmc1-probed sdhci-esdhc-imx 30b50000.*

assert_driver_present fec-driver-present fec
assert_device_present fec-ethernet0-probed fec 30be0000.*

assert_driver_present reset-imx7-driver-present reset_imx7
assert_device_present reset-imx7-probed reset_imx7 30390000.*

assert_driver_present fsl-quadspi-driver-present fsl-quadspi
assert_device_present fsl-quadspi-spi0-probed fsl-quadspi 30bb0000.*

assert_driver_present pmic-pfuze100-driver-present pfuze100-regulator
assert_device_present pmic-pfuze100-probed pfuze100-regulator 0-0008

assert_driver_present rtc-rv8803-driver-present rtc-rv8803
assert_device_present rtc-rv8803-rtc-probed rtc-rv8803 0-0032

assert_driver_present at24-driver-present at24
assert_device_present at24-eeprom0-probed at24 0-0051

assert_driver_present spi-nor-driver-present spi-nor
assert_device_present spi-nor-probed spi-nor spi0.0
